### ISSUE TITLE
Error! Failed to complete request to /api/sign-up-player: Error: socket hang up

### ISSUE THREAD

**Issue by lexcorp** [sanity-io/squizzy#23]
Error! Failed to complete request to /api/sign-up-player: Error: socket hang up
Unhandled rejection: ClientError: Unauthorized - Session not found
    at handler (/opt/squizzy/node_modules/@sanity/client/lib/http/request.js:27:13)
    at reduce (/opt/squizzy/node_modules/get-it/src/util/middlewareReducer.js:4:14)
    at Array.reduce (<anonymous>)
    at applyMiddleware (/opt/squizzy/node_modules/get-it/src/util/middlewareReducer.js:3:29)
    at onResponse (/opt/squizzy/node_modules/get-it/src/index.js:90:22)
    at cb (/opt/squizzy/node_modules/get-it/src/index.js:57:55)
    at callback (/opt/squizzy/node_modules/get-it/src/request/node-request.js:53:46)
    at /opt/squizzy/node_modules/get-it/src/request/node-request.js:141:14
    at DestroyableTransform.<anonymous> (/opt/squizzy/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:420:28) {
  response: {
    body: {
      errorCode: 'SIO-401-ANF',
      message: 'Session not found',
      statusCode: 401,
      error: 'Unauthorized'
    },
    url: 'https://84sq4q6f.api.sanity.io/v1/data/mutate/production?returnIds=true&returnDocuments=true&visibility=sync',
    method: 'POST',
    headers: {
      date: 'Fri, 23 Apr 2021 15:54:07 GMT',
      'content-type': 'application/json; charset=utf-8',
      'x-ratelimit-limit-second': '50',
      'x-ratelimit-remaining-second': '49',
      'ratelimit-remaining': '49',
      'ratelimit-limit': '50',
      'ratelimit-reset': '1',
      'content-length': '97',
      vary: 'Origin',
      xkey: 'project-84sq4q6f, project-84sq4q6f-production',
      via: '1.1 google',
      'alt-svc': 'clear',
      connection: 'close'
    },
    statusCode: 401,
    statusMessage: 'Unauthorized'
  },
  statusCode: 401,
  responseBody: '{\n' +
    '  "errorCode": "SIO-401-ANF",\n' +
    '  "message": "Session not found",\n' +
    '  "statusCode": 401,\n' +
    '  "error": "Unauthorized"\n' +
    '}'
}
Error! Failed to complete request to /api/sign-up-player: Error: socket hang up
Unhandled rejection: ClientError: Unauthorized - Session not found
    at handler (/opt/squizzy/node_modules/@sanity/client/lib/http/request.js:27:13)
    at reduce (/opt/squizzy/node_modules/get-it/src/util/middlewareReducer.js:4:14)
    at Array.reduce (<anonymous>)
    at applyMiddleware (/opt/squizzy/node_modules/get-it/src/util/middlewareReducer.js:3:29)
    at onResponse (/opt/squizzy/node_modules/get-it/src/index.js:90:22)
    at cb (/opt/squizzy/node_modules/get-it/src/index.js:57:55)
    at callback (/opt/squizzy/node_modules/get-it/src/request/node-request.js:53:46)
    at /opt/squizzy/node_modules/get-it/src/request/node-request.js:141:14
    at DestroyableTransform.<anonymous> (/opt/squizzy/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:420:28) {
  response: {
    body: {
      errorCode: 'SIO-401-ANF',
      message: 'Session not found',
      statusCode: 401,
      error: 'Unauthorized'
    },
    url: 'https://84sq4q6f.api.sanity.io/v1/data/mutate/production?returnIds=true&returnDocuments=true&visibility=sync',
    method: 'POST',
    headers: {
      date: 'Fri, 23 Apr 2021 15:54:20 GMT',
      'content-type': 'application/json; charset=utf-8',
      'x-ratelimit-limit-second': '50',
      'x-ratelimit-remaining-second': '49',
      'ratelimit-remaining': '49',
      'ratelimit-limit': '50',
      'ratelimit-reset': '1',
      'content-length': '97',
      vary: 'Origin',
      xkey: 'project-84sq4q6f, project-84sq4q6f-production',
      via: '1.1 google',
      'alt-svc': 'clear',
      connection: 'close'
    },
    statusCode: 401,
    statusMessage: 'Unauthorized'
  },
  statusCode: 401,
  responseBody: '{\n' +
    '  "errorCode": "SIO-401-ANF",\n' +
    '  "message": "Session not found",\n' +
    '  "statusCode": 401,\n' +
    '  "error": "Unauthorized"\n' +
    '}'
}
Error! Failed to complete request to /api/sign-up-player: Error: socket hang up

**Comment by lexcorp** [comment]
Add token in .env file solved problem

# Paste in token, and remove .template from the file name to make it a .env file.
# Do not commit the .env file or the token to git!
SQUIZZY_WRITE_TOKEN=token here
