### ISSUE TITLE
Error! Detecting port 45087 timed out after 300000ms

### ISSUE THREAD

**Issue by lexcorp** [sanity-io/squizzy#24]
Error! Detecting port 45087 timed out after 300000ms
Unhandled rejection: Error: Detecting port 45087 timed out after 300000ms
    at checkForPort (/usr/lib/node_modules/now/dist/index.js:224681:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at DevServer.runDevCommand (/usr/lib/node_modules/now/dist/index.js:224485:9)
    at DevServer._start (/usr/lib/node_modules/now/dist/index.js:224105:9)

**Comment by lexcorp** [comment]
Add token in .env file solved problem

# Paste in token, and remove .template from the file name to make it a .env file.
# Do not commit the .env file or the token to git!
SQUIZZY_WRITE_TOKEN=token here
